### ISSUE TITLE
IE chokes on stylesheets containing 4096 selectors, not rules

### ISSUE THREAD

**Issue by kaelig** [phamann/grunt-css-metrics#2]
As per this blog's review of some always interesting IE bugs, it seems IE chokes on a maximum number of selectors, and not rules: http://blogs.telerik.com/aspnet-ajax/posts/10-05-03/internet-explorer-css-limits.aspx

**Comment by misterbrownlee** [comment]
This was fixed in 0d8263019c37062f8b23a0fd4211336795115c4d :)

**Comment by kaelig** [comment]
Closing this as it seems like it was fixed!
