### ISSUE TITLE
move the core metrics lib into a separate package

### ISSUE THREAD

**Issue by necolas** [phamann/grunt-css-metrics#7]
should be a dependency of the grunt plugin, that way other people can use or wrap the metrics module without all the grunt baggage.

**Comment by phamann** [comment]
This already exists in the flavour of:
- [CSS Metrics](https://github.com/rquinlivan/css-metrics)

which in turn uses:
- [CSS Parse](https://github.com/reworkcss/css-parse)

I have merely wrapped Grunt around these (albeit re-wrote a bit of CSSMetrics lib to play nicely. Hence why its not included as a dependency).

**Comment by necolas** [comment]
I see. Any interest in up-streaming the changes to CSSMetrics?
